import type { GlossaryEntry } from './GlossaryTypes'

export const BUILTIN_PHRASES: GlossaryEntry[] = [
  { source: 'command not found', target: '命令未找到' },
  { source: 'permission denied', target: '权限不足' },
  { source: 'No such file or directory', target: '没有该文件或目录' },
  { source: 'file exists', target: '文件已存在' },
  { source: 'is a directory', target: '是一个目录' },
  { source: 'not a directory', target: '不是目录' },
  { source: 'operation not permitted', target: '不允许的操作' },
  { source: 'read-only file system', target: '只读文件系统' },
  { source: 'device or resource busy', target: '设备或资源忙' },
  { source: 'broken pipe', target: '管道已断开' },
  { source: 'connection refused', target: '连接被拒绝' },
  { source: 'connection reset', target: '连接被重置' },
  { source: 'connection timed out', target: '连接超时' },
  { source: 'network is unreachable', target: '网络不可达' },
  { source: 'host not found', target: '未找到主机' },
  { source: 'name or service not known', target: '名称或服务未知' },
  { source: 'invalid argument', target: '参数无效' },
  { source: 'bad file descriptor', target: '文件描述符错误' },
  { source: 'no space left on device', target: '设备空间不足' },
  { source: 'disk quota exceeded', target: '超出磁盘配额' },
  { source: 'out of memory', target: '内存不足' },
  { source: 'segmentation fault', target: '段错误' },
  { source: 'syntax error', target: '语法错误' },
  { source: 'failed to', target: '失败' },
  { source: 'failed to load', target: '加载失败' },
  { source: 'authentication failed', target: '认证失败' },
  { source: 'invalid credentials', target: '凭据无效' },
  { source: 'token expired', target: '令牌已过期' },
  { source: 'request timeout', target: '请求超时' },
  { source: 'too many requests', target: '请求过于频繁' },
  { source: 'service unavailable', target: '服务不可用' },
  { source: 'internal server error', target: '服务器内部错误' },
  { source: 'bad gateway', target: '网关错误' },
  { source: 'gateway timeout', target: '网关超时' },
  { source: 'access denied', target: '拒绝访问' },
  { source: 'unauthorized', target: '未授权' },
  { source: 'forbidden', target: '禁止访问' },
  { source: 'not authorized', target: '未被授权' },
  { source: 'timeout exceeded', target: '超出超时限制' },
  { source: 'permission required', target: '需要权限' },
  { source: 'unknown error', target: '未知错误' },
  { source: 'unexpected error', target: '意外错误' },
  { source: 'failed', target: '失败', uiOnly: true, wholeWord: true },
  { source: 'error', target: '错误', uiOnly: true, wholeWord: true },
  { source: 'warning', target: '警告', uiOnly: true, wholeWord: true },
  { source: 'fatal', target: '严重错误', uiOnly: true, wholeWord: true },
  { source: 'conflict', target: '冲突', uiOnly: true, wholeWord: true },
  { source: 'retrying', target: '正在重试', uiOnly: true, wholeWord: true },
  { source: 'retry', target: '重试', uiOnly: true, wholeWord: true },
  { source: 'cancelled', target: '已取消', uiOnly: true, wholeWord: true },
  { source: 'canceled', target: '已取消', uiOnly: true, wholeWord: true },
  { source: 'aborted', target: '已中止', uiOnly: true, wholeWord: true },
  { source: 'disconnected', target: '已断开', uiOnly: true, wholeWord: true },
  { source: 'unavailable', target: '不可用', uiOnly: true, wholeWord: true },
  { source: 'loading...', target: '加载中...' },
  { source: 'loading', target: '加载中', uiOnly: true, wholeWord: true },
  { source: 'processing', target: '处理中', uiOnly: true, wholeWord: true },
  { source: 'connecting', target: '连接中', uiOnly: true, wholeWord: true },
  { source: 'connected', target: '已连接', uiOnly: true, wholeWord: true },
  { source: 'disconnecting', target: '断开中', uiOnly: true, wholeWord: true },
  { source: 'reconnecting', target: '重连中', uiOnly: true, wholeWord: true },
  { source: 'syncing', target: '同步中', uiOnly: true, wholeWord: true },
  { source: 'synced', target: '已同步', uiOnly: true, wholeWord: true },
  { source: 'initializing', target: '初始化中', uiOnly: true, wholeWord: true },
  { source: 'starting', target: '启动中', uiOnly: true, wholeWord: true },
  { source: 'stopping', target: '停止中', uiOnly: true, wholeWord: true },
  { source: 'running', target: '运行中', uiOnly: true, wholeWord: true },
  { source: 'pending', target: '等待中', uiOnly: true, wholeWord: true },
  { source: 'queued', target: '排队中', uiOnly: true, wholeWord: true },
  { source: 'in progress', target: '进行中' },
  { source: 'please wait', target: '请稍候' },
  { source: 'ready', target: '就绪', uiOnly: true, wholeWord: true },
  { source: 'complete', target: '完成', uiOnly: true, wholeWord: true },
  { source: 'completed', target: '已完成', uiOnly: true, wholeWord: true },
  { source: 'success', target: '成功', uiOnly: true, wholeWord: true },
  { source: 'succeeded', target: '已成功', uiOnly: true, wholeWord: true },
  { source: 'done', target: '完成', uiOnly: true, wholeWord: true },
  { source: 'offline', target: '离线', uiOnly: true, wholeWord: true },
  { source: 'online', target: '在线', uiOnly: true, wholeWord: true },
  { source: 'waiting for input', target: '等待输入' },
  { source: 'no results', target: '无结果' },
  { source: 'empty', target: '空', uiOnly: true, wholeWord: true },
  { source: 'copied', target: '已复制', uiOnly: true, wholeWord: true },
  { source: 'pasted', target: '已粘贴', uiOnly: true, wholeWord: true },
  { source: 'saved', target: '已保存', uiOnly: true, wholeWord: true },
  { source: 'save failed', target: '保存失败' },
  { source: 'updated', target: '已更新', uiOnly: true, wholeWord: true },
  { source: 'update available', target: '有可用更新' },
  { source: 'update failed', target: '更新失败' },
  { source: 'download failed', target: '下载失败' },
  { source: 'uploading', target: '上传中', uiOnly: true, wholeWord: true },
  { source: 'downloading', target: '下载中', uiOnly: true, wholeWord: true },
  { source: 'verifying', target: '校验中', uiOnly: true, wholeWord: true },
  { source: 'validated', target: '已校验', uiOnly: true, wholeWord: true },
  { source: 'invalid input', target: '输入无效' },
  { source: 'continue anyway', target: '仍然继续' },
  { source: 'Continue', target: '继续', uiOnly: true, wholeWord: true },
  { source: 'Back', target: '返回', uiOnly: true, wholeWord: true },
  { source: 'Cancel', target: '取消', uiOnly: true, wholeWord: true },
  { source: 'Help', target: '帮助', uiOnly: true, wholeWord: true },
  { source: 'Settings', target: '设置', uiOnly: true, wholeWord: true },
  { source: 'Quit', target: '退出', uiOnly: true, wholeWord: true },
  { source: 'Exit', target: '退出', uiOnly: true, wholeWord: true },
  { source: 'Confirm', target: '确认', uiOnly: true, wholeWord: true },
  { source: 'Apply', target: '应用', uiOnly: true, wholeWord: true },
  { source: 'Save', target: '保存', uiOnly: true, wholeWord: true },
  { source: 'Discard', target: '放弃', uiOnly: true, wholeWord: true },
  { source: 'Next', target: '下一步', uiOnly: true, wholeWord: true },
  { source: 'Previous', target: '上一步', uiOnly: true, wholeWord: true },
  { source: 'Submit', target: '提交', uiOnly: true, wholeWord: true },
  { source: 'Open', target: '打开', uiOnly: true, wholeWord: true },
  { source: 'Close', target: '关闭', uiOnly: true, wholeWord: true },
  { source: 'Search', target: '搜索', uiOnly: true, wholeWord: true },
  { source: 'Filter', target: '筛选', uiOnly: true, wholeWord: true },
  { source: 'Clear', target: '清除', uiOnly: true, wholeWord: true },
  { source: 'Refresh', target: '刷新', uiOnly: true, wholeWord: true },
  { source: 'Enable', target: '启用', uiOnly: true, wholeWord: true },
  { source: 'Disable', target: '禁用', uiOnly: true, wholeWord: true },
  { source: 'Show more', target: '显示更多' },
  { source: 'Show less', target: '显示更少' },
  { source: 'Select all', target: '全选' },
  { source: 'Select', target: '选择', uiOnly: true, wholeWord: true },
  { source: 'Deselect', target: '取消选择', uiOnly: true, wholeWord: true },
  { source: 'Edit', target: '编辑', uiOnly: true, wholeWord: true },
  { source: 'Delete', target: '删除', uiOnly: true, wholeWord: true },
  { source: 'Remove', target: '移除', uiOnly: true, wholeWord: true },
  { source: 'Add', target: '添加', uiOnly: true, wholeWord: true },
  { source: 'Create', target: '创建', uiOnly: true, wholeWord: true },
  { source: 'New session', target: '新会话' },
  { source: 'Resume', target: '继续', uiOnly: true, wholeWord: true },
  { source: 'Pause', target: '暂停', uiOnly: true, wholeWord: true },
  { source: 'Stop', target: '停止', uiOnly: true, wholeWord: true },
  { source: 'Start', target: '开始', uiOnly: true, wholeWord: true },
  { source: 'Details', target: '详情', uiOnly: true, wholeWord: true },
  { source: 'View details', target: '查看详情' },
  { source: 'Copy', target: '复制', uiOnly: true, wholeWord: true },
  { source: 'Paste', target: '粘贴', uiOnly: true, wholeWord: true },
  { source: 'Export', target: '导出', uiOnly: true, wholeWord: true },
  { source: 'Import', target: '导入', uiOnly: true, wholeWord: true },
  { source: 'Reload', target: '重新加载', uiOnly: true, wholeWord: true },
  { source: 'Reset', target: '重置', uiOnly: true, wholeWord: true },
  { source: 'Skip', target: '跳过', uiOnly: true, wholeWord: true },
  { source: 'Ask anything...', target: '在这里提问...' },
  { source: 'Ask anything…', target: '在这里提问…' },
  { source: 'Tip Press', target: '提示 按下' },
  { source: 'Press Enter to continue', target: '按 Enter 继续' },
  { source: 'Press any key to continue', target: '按任意键继续' },
  { source: 'Press q to quit', target: '按 q 退出' },
  { source: 'Press Ctrl+C to cancel', target: '按 Ctrl+C 取消' },
  { source: 'Press Esc to close', target: '按 Esc 关闭' },
  { source: 'Use arrow keys to navigate', target: '使用方向键导航' },
  { source: 'Use Tab to switch', target: '使用 Tab 切换' },
  { source: 'Type to search', target: '输入以搜索' },
  { source: 'No items', target: '没有项目' },
  { source: 'No matching items', target: '没有匹配项' },
  { source: 'Select an option', target: '请选择一个选项' },
  { source: 'Choose an option', target: '选择一个选项' },
  { source: 'Are you sure?', target: '确定吗？' },
  { source: 'Confirm action', target: '确认操作' },
  { source: 'View logs', target: '查看日志' },
  { source: 'Open logs', target: '打开日志' },
  { source: 'Hide details', target: '隐藏详情' },
  { source: 'Show details', target: '显示详情' },
  { source: 'Try again later', target: '请稍后重试' },
  { source: 'Check your connection', target: '请检查网络连接' },
  { source: 'New chat', target: '新建对话' },
  { source: 'New conversation', target: '新建会话' },
  { source: 'Conversation', target: '会话', uiOnly: true, wholeWord: true },
  { source: 'Conversations', target: '会话列表' },
  { source: 'History', target: '历史记录', uiOnly: true, wholeWord: true },
  { source: 'Recent', target: '最近', uiOnly: true, wholeWord: true },
  { source: 'Messages', target: '消息', uiOnly: true, wholeWord: true },
  { source: 'Message', target: '消息', uiOnly: true, wholeWord: true },
  { source: 'Assistant', target: '助手', uiOnly: true, wholeWord: true },
  { source: 'User', target: '用户', uiOnly: true, wholeWord: true },
  { source: 'System', target: '系统', uiOnly: true, wholeWord: true },
  { source: 'Prompt', target: '提示词', uiOnly: true, wholeWord: true },
  { source: 'System prompt', target: '系统提示词' },
  { source: 'User prompt', target: '用户提示词' },
  { source: 'Context', target: '上下文', uiOnly: true, wholeWord: true },
  { source: 'Context window', target: '上下文窗口' },
  { source: 'Workspace', target: '工作区', uiOnly: true, wholeWord: true },
  { source: 'Project', target: '项目', uiOnly: true, wholeWord: true },
  { source: 'Projects', target: '项目列表' },
  { source: 'Files', target: '文件', uiOnly: true, wholeWord: true },
  { source: 'File', target: '文件', uiOnly: true, wholeWord: true },
  { source: 'Open file', target: '打开文件' },
  { source: 'Open folder', target: '打开文件夹' },
  { source: 'Read-only mode', target: '只读模式' },
  { source: 'Plan mode', target: '计划模式' },
  { source: 'Build mode', target: '构建模式' },
  { source: 'Debug mode', target: '调试模式' },
  { source: 'Thinking', target: '思考中', uiOnly: true, wholeWord: true },
  { source: 'Generating', target: '生成中', uiOnly: true, wholeWord: true },
  { source: 'Analyzing', target: '分析中', uiOnly: true, wholeWord: true },
  { source: 'Summarizing', target: '总结中', uiOnly: true, wholeWord: true },
  { source: 'Planning', target: '规划中', uiOnly: true, wholeWord: true },
  { source: 'Executing', target: '执行中', uiOnly: true, wholeWord: true },
  { source: 'Running command', target: '正在运行命令' },
  { source: 'Run command', target: '运行命令' },
  { source: 'Command', target: '命令', uiOnly: true, wholeWord: true },
  { source: 'Commands', target: '命令列表' },
  { source: 'Terminal', target: '终端', uiOnly: true, wholeWord: true },
  { source: 'Output', target: '输出', uiOnly: true, wholeWord: true },
  { source: 'Input', target: '输入', uiOnly: true, wholeWord: true },
  { source: 'Token', target: '令牌', uiOnly: true, wholeWord: true },
  { source: 'Tokens', target: '令牌', uiOnly: true, wholeWord: true },
  { source: 'Model', target: '模型', uiOnly: true, wholeWord: true },
  { source: 'Provider', target: '提供方', uiOnly: true, wholeWord: true },
  { source: 'Session', target: '会话', uiOnly: true, wholeWord: true },
  { source: 'Sessions', target: '会话列表' },
  { source: 'Switch session', target: '切换会话' },
  { source: 'Resume session', target: '恢复会话' },
  { source: 'Restore session', target: '恢复会话' },
  { source: 'Loading session', target: '加载会话中' },
  { source: 'Restoring session', target: '恢复会话中' },
  { source: 'Session restored', target: '会话已恢复' },
  { source: 'Session expired', target: '会话已过期' },
  { source: 'Waiting for approval', target: '等待批准' },
  { source: 'Approval required', target: '需要批准' },
  { source: 'Approve', target: '批准', uiOnly: true, wholeWord: true },
  { source: 'Reject', target: '拒绝', uiOnly: true, wholeWord: true },
  { source: 'Deny', target: '拒绝', uiOnly: true, wholeWord: true },
  { source: 'Allow', target: '允许', uiOnly: true, wholeWord: true },
  { source: 'Allowed', target: '已允许', uiOnly: true, wholeWord: true },
  { source: 'Denied', target: '已拒绝', uiOnly: true, wholeWord: true },
  { source: 'Approved', target: '已批准', uiOnly: true, wholeWord: true },
  { source: 'Rejected', target: '已拒绝', uiOnly: true, wholeWord: true },
  { source: 'Auto approve', target: '自动批准' },
  { source: 'Manual approval', target: '手动批准' },
  { source: 'Policy blocked', target: '策略阻止' },
  { source: 'Blocked by policy', target: '被策略阻止' },
  { source: 'Patch', target: '补丁', uiOnly: true, wholeWord: true },
  { source: 'Apply patch', target: '应用补丁' },
  { source: 'Patch applied', target: '补丁已应用' },
  { source: 'Patch failed', target: '补丁应用失败' },
  { source: 'Diff', target: '差异', uiOnly: true, wholeWord: true },
  { source: 'Changes', target: '变更', uiOnly: true, wholeWord: true },
  { source: 'No changes', target: '无变更' },
  { source: 'Review', target: '审查', uiOnly: true, wholeWord: true },
  { source: 'Reviewed', target: '已审查', uiOnly: true, wholeWord: true },
  { source: 'Accepted', target: '已接受', uiOnly: true, wholeWord: true },
  { source: 'Declined', target: '已拒绝', uiOnly: true, wholeWord: true },
  { source: 'Skipped', target: '已跳过', uiOnly: true, wholeWord: true },
  { source: 'Reason', target: '原因', uiOnly: true, wholeWord: true },
  { source: 'Summary', target: '摘要', uiOnly: true, wholeWord: true },
  { source: 'Details', target: '详情', uiOnly: true, wholeWord: true },
  { source: 'Command palette', target: '命令面板' },
  { source: 'Keyboard shortcuts', target: '快捷键' },
  { source: 'Shortcuts', target: '快捷键', uiOnly: true, wholeWord: true },
  { source: 'Toggle debug', target: '切换调试' },
  { source: 'Open settings', target: '打开设置' },
  { source: 'Version', target: '版本', uiOnly: true, wholeWord: true },
  { source: 'Account', target: '账户', uiOnly: true, wholeWord: true },
  { source: 'Profile', target: '配置', uiOnly: true, wholeWord: true },
  { source: 'Organization', target: '组织', uiOnly: true, wholeWord: true },
  { source: 'Sign in', target: '登录' },
  { source: 'Sign out', target: '退出登录' },
  { source: 'Login required', target: '需要登录' },
  { source: 'Authentication required', target: '需要认证' },
  { source: 'Open recent', target: '打开最近项目' },
  { source: 'Working directory', target: '工作目录' },
  { source: 'Current directory', target: '当前目录' },
  { source: 'No tasks', target: '无任务' },
  { source: 'Task', target: '任务', uiOnly: true, wholeWord: true },
  { source: 'Tasks', target: '任务列表' },
  { source: 'Retry failed tasks', target: '重试失败任务' },
  { source: 'Waiting', target: '等待中', uiOnly: true, wholeWord: true },
  { source: 'Queued', target: '排队中', uiOnly: true, wholeWord: true },
  { source: 'Interrupted', target: '已中断', uiOnly: true, wholeWord: true },
  { source: 'Completed in', target: '完成耗时' },
  { source: 'Elapsed', target: '耗时', uiOnly: true, wholeWord: true },
  { source: 'Duration', target: '持续时间', uiOnly: true, wholeWord: true },
  { source: 'No data', target: '无数据' },
  { source: 'Not available', target: '不可用' },
  { source: 'Try a different query', target: '请尝试其他查询' },
  { source: 'Press / to search', target: '按 / 搜索' },
  { source: 'Press ? for help', target: '按 ? 查看帮助' },
  { source: 'Press Enter to submit', target: '按 Enter 提交' },
  { source: 'Press Ctrl+C to exit', target: '按 Ctrl+C 退出' },
  { source: 'Press Ctrl+L to clear', target: '按 Ctrl+L 清屏' },
  { source: 'Use arrows to move', target: '使用方向键移动' },
  { source: 'Type your message', target: '输入你的消息' },
  { source: 'Type a message', target: '输入消息' },
  { source: 'Start typing', target: '开始输入' },
  { source: 'Nothing selected', target: '未选择任何项' },
  { source: 'Selected', target: '已选择', uiOnly: true, wholeWord: true },
  { source: 'Open in editor', target: '在编辑器中打开' },
  { source: 'Open terminal', target: '打开终端' },
  { source: 'Inspect', target: '查看', uiOnly: true, wholeWord: true },
  { source: 'Expand', target: '展开', uiOnly: true, wholeWord: true },
  { source: 'Collapse', target: '折叠', uiOnly: true, wholeWord: true },
  { source: 'Load more', target: '加载更多' },
  { source: 'No preview', target: '无预览' },
  { source: 'Preview', target: '预览', uiOnly: true, wholeWord: true },
  { source: 'Sending', target: '发送中', uiOnly: true, wholeWord: true },
  { source: 'Sent', target: '已发送', uiOnly: true, wholeWord: true },
  { source: 'Receiving', target: '接收中', uiOnly: true, wholeWord: true },
  { source: 'Received', target: '已接收', uiOnly: true, wholeWord: true },
  { source: 'No connection', target: '无连接' },
  { source: 'Connection lost', target: '连接已断开' },
  { source: 'Reconnect', target: '重新连接', uiOnly: true, wholeWord: true },
  { source: 'Working...', target: '处理中...' },
  { source: 'Please try again', target: '请重试' },
  { source: 'View all', target: '查看全部' },
  { source: 'Hide', target: '隐藏', uiOnly: true, wholeWord: true },
  { source: 'Show', target: '显示', uiOnly: true, wholeWord: true },
  { source: 'Default', target: '默认', uiOnly: true, wholeWord: true },
  { source: 'Custom', target: '自定义', uiOnly: true, wholeWord: true },
  { source: 'Enabled', target: '已启用', uiOnly: true, wholeWord: true },
  { source: 'Disabled', target: '已禁用', uiOnly: true, wholeWord: true },
  { source: 'Unknown', target: '未知', uiOnly: true, wholeWord: true },
  { source: 'Not found', target: '未找到' },
  { source: 'Try another option', target: '请尝试其他选项' },
  { source: 'Back to top', target: '返回顶部' },
  { source: 'Go back', target: '返回' },
  { source: 'Go forward', target: '前进' },
  { source: 'Home', target: '首页', uiOnly: true, wholeWord: true },
  { source: 'Welcome', target: '欢迎', uiOnly: true, wholeWord: true },
  { source: 'Welcome back', target: '欢迎回来' },
  { source: 'Get started', target: '开始使用' },
  { source: 'Getting started', target: '开始使用中' },
  { source: 'What would you like to do?', target: '你想做什么？' },
  { source: 'Choose a task', target: '选择一个任务' },
  { source: 'Select a file', target: '选择文件' },
  { source: 'Select a directory', target: '选择目录' },
  { source: 'Open project', target: '打开项目' },
  { source: 'Project not found', target: '未找到项目' },
  { source: 'Workspace not found', target: '未找到工作区' },
  { source: 'No workspace selected', target: '未选择工作区' },
  { source: 'Switch workspace', target: '切换工作区' },
  { source: 'Clear history', target: '清除历史' },
  { source: 'Delete history', target: '删除历史' },
  { source: 'Show history', target: '显示历史' },
  { source: 'Open history', target: '打开历史' },
  { source: 'No conversation selected', target: '未选择会话' },
  { source: 'No message selected', target: '未选择消息' },
  { source: 'Continue generating', target: '继续生成' },
  { source: 'Stop generating', target: '停止生成' },
  { source: 'Regenerate', target: '重新生成', uiOnly: true, wholeWord: true },
  { source: 'Regenerate response', target: '重新生成回复' },
  { source: 'Copied to clipboard', target: '已复制到剪贴板' },
  { source: 'Copy failed', target: '复制失败' },
  { source: 'Paste failed', target: '粘贴失败' },
  { source: 'Open command menu', target: '打开命令菜单' },
  { source: 'Switch model', target: '切换模型' },
  { source: 'Model not available', target: '模型不可用' },
  { source: 'Provider unavailable', target: '提供方不可用' },
  { source: 'Rate limited', target: '触发限流' },
  { source: 'Quota exceeded', target: '超出配额' },
  { source: 'Temporary error', target: '临时错误' },
  { source: 'Server busy', target: '服务器繁忙' },
  { source: 'Please retry', target: '请重试' },
  { source: 'Operation completed', target: '操作完成' },
  { source: 'Operation failed', target: '操作失败' },
  { source: 'Operation cancelled', target: '操作已取消' },
  { source: 'Operation aborted', target: '操作已中止' },
  { source: 'Retry operation', target: '重试操作' },
  { source: 'Apply changes', target: '应用变更' },
  { source: 'Discard changes', target: '放弃变更' },
  { source: 'Review changes', target: '审查变更' },
  { source: 'No pending changes', target: '无待处理变更' },
  { source: 'Ready to continue', target: '准备继续' },
  { source: 'All done', target: '全部完成' },
  { source: 'Done for now', target: '暂时完成' },
  { source: 'Need anything else?', target: '还需要其他帮助吗？' },
  { source: 'Ask a follow-up', target: '继续追问' },
  { source: 'Follow-up', target: '追问', uiOnly: true, wholeWord: true },
  { source: 'Start over', target: '重新开始' },
  { source: 'Reset session', target: '重置会话' },
  { source: 'Session reset', target: '会话已重置' },
  { source: 'Open sidebar', target: '打开侧边栏' },
  { source: 'Close sidebar', target: '关闭侧边栏' },
  { source: 'Sidebar', target: '侧边栏', uiOnly: true, wholeWord: true },
  { source: 'Panel', target: '面板', uiOnly: true, wholeWord: true },
  { source: 'Status', target: '状态', uiOnly: true, wholeWord: true },
  { source: 'Status bar', target: '状态栏' },
  { source: 'Agent status', target: '代理状态' },
  { source: 'Ready for input', target: '等待输入' },
  { source: 'Waiting for response', target: '等待响应' },
  { source: 'Response received', target: '已收到响应' },
  { source: 'No response', target: '无响应' },
  { source: 'Stop here', target: '到此停止' },
  { source: 'Continue here', target: '从此继续' },
  { source: 'Open in browser', target: '在浏览器中打开' },
  { source: 'Open documentation', target: '打开文档' },
  { source: 'Documentation', target: '文档', uiOnly: true, wholeWord: true },
  { source: 'Learn more', target: '了解更多' },
  { source: 'View full output', target: '查看完整输出' },
  { source: 'More actions', target: '更多操作' },
  { source: 'Actions', target: '操作', uiOnly: true, wholeWord: true },
  { source: 'Nothing to show', target: '没有可显示内容' },
  { source: 'No output', target: '无输出' },
  { source: 'Output truncated', target: '输出已截断' },
  { source: 'Waiting for terminal', target: '等待终端' },
  { source: 'Terminal ready', target: '终端就绪' },
  { source: 'Terminal disconnected', target: '终端已断开' },
  { source: 'Reconnect terminal', target: '重新连接终端' },
  { source: 'Keep waiting', target: '继续等待' },
  { source: 'Skip for now', target: '暂时跳过' },
  { source: 'Open menu', target: '打开菜单' },
  { source: 'Close menu', target: '关闭菜单' },
  { source: 'Menu', target: '菜单', uiOnly: true, wholeWord: true },
  { source: 'Select language', target: '选择语言' },
  { source: 'Language', target: '语言', uiOnly: true, wholeWord: true },
  { source: 'Theme', target: '主题', uiOnly: true, wholeWord: true },
  { source: 'Light', target: '浅色', uiOnly: true, wholeWord: true },
  { source: 'Dark', target: '深色', uiOnly: true, wholeWord: true },
  { source: 'Auto', target: '自动', uiOnly: true, wholeWord: true },
  { source: 'Search results', target: '搜索结果' },
  { source: 'No search results', target: '无搜索结果' },
  { source: 'Apply filter', target: '应用筛选' },
  { source: 'Clear filter', target: '清除筛选' },
  { source: 'Open task', target: '打开任务' },
  { source: 'Task details', target: '任务详情' },
  { source: 'Task failed', target: '任务失败' },
  { source: 'Task completed', target: '任务已完成' },
  { source: 'Task cancelled', target: '任务已取消' },
  { source: 'Task running', target: '任务运行中' },
  { source: 'No tasks running', target: '无运行中的任务' },
  { source: 'Ready to run', target: '准备运行' },
  { source: 'Run', target: '运行', uiOnly: true, wholeWord: true },
  { source: 'Stop run', target: '停止运行' },
  { source: 'Run again', target: '再次运行' },
  { source: 'Open terminal output', target: '打开终端输出' },
  { source: 'No terminal output yet', target: '暂无终端输出' },
  { source: 'Start a new task', target: '开始新任务' },
  { source: 'Choose a command', target: '选择命令' },
  { source: 'No command selected', target: '未选择命令' },
  { source: 'Command completed', target: '命令已完成' },
  { source: 'Command failed', target: '命令失败' },
  { source: 'Command cancelled', target: '命令已取消' },
  { source: 'Retry command', target: '重试命令' },
  { source: 'Open command history', target: '打开命令历史' },
  { source: 'Command history', target: '命令历史' },
  { source: 'Clear command history', target: '清除命令历史' },
  { source: 'No command history', target: '无命令历史' },
  { source: 'Type a command', target: '输入命令' },
  { source: 'Enter command', target: '输入命令' },
  { source: 'Ready for command', target: '等待命令' },
  { source: 'Use ↑ ↓ to navigate', target: '使用 ↑ ↓ 导航' },
  { source: 'Use Enter to select', target: '使用 Enter 选择' },
  { source: 'Use Esc to cancel', target: '使用 Esc 取消' },
  { source: 'Open source', target: '打开源内容' },
  { source: 'Open destination', target: '打开目标位置' },
  { source: 'Go to line', target: '跳转到行' },
  { source: 'Line', target: '行', uiOnly: true, wholeWord: true },
  { source: 'Column', target: '列', uiOnly: true, wholeWord: true },
  { source: 'Lines', target: '行数', uiOnly: true, wholeWord: true },
  { source: 'Columns', target: '列数', uiOnly: true, wholeWord: true },
  { source: 'No line selected', target: '未选择行' },
  { source: 'Open file location', target: '打开文件位置' },
  { source: 'Reveal in finder', target: '在访达中显示' },
  { source: 'Reveal in explorer', target: '在资源管理器中显示' },
  { source: 'Open containing folder', target: '打开所在文件夹' },
  { source: 'Copied path', target: '已复制路径' },
  { source: 'Copy path', target: '复制路径' },
  { source: 'Copy output', target: '复制输出' },
  { source: 'Clear output', target: '清除输出' },
  { source: 'Open output', target: '打开输出' },
  { source: 'Hide output', target: '隐藏输出' },
  { source: 'Show output', target: '显示输出' },
  { source: 'Output ready', target: '输出就绪' },
  { source: 'Output updated', target: '输出已更新' },
  { source: 'Output failed', target: '输出失败' },
  { source: 'No suggestions', target: '无建议' },
  { source: 'Suggestions', target: '建议', uiOnly: true, wholeWord: true },
  { source: 'Try this', target: '试试这个' },
  { source: 'Recommended', target: '推荐', uiOnly: true, wholeWord: true },
  { source: 'Recommended action', target: '推荐操作' },
  { source: 'Open recommendation', target: '打开推荐项' },
  { source: 'Dismiss', target: '忽略', uiOnly: true, wholeWord: true },
  { source: 'Dismiss all', target: '全部忽略' },
  { source: 'Need help?', target: '需要帮助吗？' },
  { source: 'Show help', target: '显示帮助' },
  { source: 'Hide help', target: '隐藏帮助' },
  { source: 'Open help', target: '打开帮助' },
  { source: 'Back to previous', target: '返回上一步' },
  { source: 'Go to next', target: '前往下一项' },
  { source: 'Close this panel', target: '关闭此面板' },
  { source: 'Open this panel', target: '打开此面板' },
  { source: 'Start here', target: '从这里开始' },
  { source: 'Continue here', target: '从这里继续' },
  { source: 'Nothing else to show', target: '没有更多内容' },
  { source: 'All caught up', target: '已全部处理' },
  { source: 'Session complete', target: '会话完成' },
  { source: 'Session failed', target: '会话失败' },
  { source: 'Session cancelled', target: '会话已取消' },
  { source: 'Session running', target: '会话进行中' },
  { source: 'Session paused', target: '会话已暂停' },
  { source: 'Session resumed', target: '会话已恢复' },
  { source: 'Reload session', target: '重新加载会话' },
  { source: 'Reload required', target: '需要重新加载' },
  { source: 'Restart required', target: '需要重启' },
  { source: 'Restart now', target: '立即重启' },
  { source: 'Later', target: '稍后', uiOnly: true, wholeWord: true },
  { source: 'Now', target: '现在', uiOnly: true, wholeWord: true },
  { source: 'Never', target: '从不', uiOnly: true, wholeWord: true },
  { source: 'Always', target: '总是', uiOnly: true, wholeWord: true },
  { source: 'Once', target: '一次', uiOnly: true, wholeWord: true },
  { source: 'Only this time', target: '仅这一次' },
  { source: 'Remember my choice', target: '记住我的选择' },
  { source: 'Do not ask again', target: '不再询问' },
  { source: 'Continue with caution', target: '谨慎继续' },
  { source: 'Unsafe operation', target: '不安全操作' },
  { source: 'Safe mode', target: '安全模式' },
  { source: 'Sandbox', target: '沙箱', uiOnly: true, wholeWord: true },
  { source: 'Escalation', target: '提权', uiOnly: true, wholeWord: true },
  { source: 'Needs escalation', target: '需要提权' },
  { source: 'Escalation denied', target: '提权被拒绝' },
  { source: 'Escalation approved', target: '提权已批准' },
  { source: 'Grant permission', target: '授予权限' },
  { source: 'Revoke permission', target: '撤销权限' },
  { source: 'Permission granted', target: '权限已授予' },
  { source: 'Permission revoked', target: '权限已撤销' },
  { source: 'No permission', target: '无权限' },
  { source: 'Permission missing', target: '缺少权限' },
  { source: 'Try with elevated access', target: '请尝试更高权限' },
  { source: 'Open permissions', target: '打开权限设置' },
  { source: 'Permission settings', target: '权限设置' },
  { source: 'Back to terminal', target: '返回终端' },
  { source: 'Open translated mirror', target: '打开翻译镜像' },
  { source: 'Translation', target: '翻译', uiOnly: true, wholeWord: true },
  { source: 'Translated', target: '已翻译', uiOnly: true, wholeWord: true },
  { source: 'Not translated', target: '未翻译' },
  { source: 'Translation unavailable', target: '翻译不可用' },
  { source: 'Show original', target: '显示原文' },
  { source: 'Show translation', target: '显示翻译' },
  { source: 'Original', target: '原文', uiOnly: true, wholeWord: true },
  { source: 'Full translation', target: '完整翻译' },
  { source: 'View full translation', target: '查看完整翻译' },
  { source: 'Translation marker', target: '翻译标记' },
  { source: 'No translatable text', target: '没有可翻译文本' },
  { source: 'Translation updated', target: '翻译已更新' },
  { source: 'Translation failed', target: '翻译失败' },
  { source: 'Reload translations', target: '重新加载翻译' },
  { source: 'Glossary', target: '术语表', uiOnly: true, wholeWord: true },
  { source: 'Glossary loaded', target: '术语表已加载' },
  { source: 'Glossary reloaded', target: '术语表已重载' },
  { source: 'Glossary import failed', target: '术语表导入失败' },
  { source: 'Glossary exported', target: '术语表已导出' },
  { source: 'Glossary path', target: '术语表路径' },
  { source: 'Reload glossary', target: '重载术语表' },
  { source: 'Import glossary', target: '导入术语表' },
  { source: 'Export glossary', target: '导出术语表' },
  { source: 'Debug', target: '调试', uiOnly: true, wholeWord: true },
  { source: 'Metrics', target: '指标', uiOnly: true, wholeWord: true },
  { source: 'Scan runs', target: '扫描次数' },
  { source: 'Candidates found', target: '候选命中数' },
  { source: 'Markers rendered', target: '标记数量' },
  { source: 'Skip reasons', target: '跳过原因' },
  { source: 'No skip reasons', target: '无跳过原因' },
  { source: 'Ready for translation', target: '准备翻译' },
  { source: 'Waiting for terminal output', target: '等待终端输出' },
  { source: 'Open debugger', target: '打开调试器' },
  { source: 'Close debugger', target: '关闭调试器' },
  { source: 'Debugger', target: '调试器', uiOnly: true, wholeWord: true },
  { source: 'Done loading', target: '加载完成' },
  { source: 'Still loading', target: '仍在加载' },
  { source: 'Loading complete', target: '加载完成' },
  { source: 'No more items', target: '没有更多项目' },
  { source: 'Expand all', target: '展开全部' },
  { source: 'Collapse all', target: '折叠全部' },
  { source: 'Scroll to bottom', target: '滚动到底部' },
  { source: 'Scroll to top', target: '滚动到顶部' },
  { source: 'Jump to latest', target: '跳到最新' },
  { source: 'Return to latest', target: '返回最新位置' },
  { source: 'Open latest output', target: '打开最新输出' },
  { source: 'Latest', target: '最新', uiOnly: true, wholeWord: true },
  { source: 'Older', target: '更早', uiOnly: true, wholeWord: true },
  { source: 'Newest', target: '最新', uiOnly: true, wholeWord: true },
  { source: 'Oldest', target: '最早', uiOnly: true, wholeWord: true },
  { source: 'No older items', target: '没有更早内容' },
  { source: 'No newer items', target: '没有更新内容' },
  { source: 'Ready when you are', target: '已准备好，等待你的输入' },
  { source: 'What next?', target: '下一步做什么？' },
  { source: 'Choose next action', target: '选择下一步操作' },
  { source: 'Continue to next step', target: '继续下一步' },
  { source: 'Back to previous step', target: '返回上一步' },
  { source: 'Step completed', target: '步骤已完成' },
  { source: 'Step failed', target: '步骤失败' },
  { source: 'Step skipped', target: '步骤已跳过' },
  { source: 'No steps available', target: '没有可用步骤' },
  { source: 'Open step details', target: '打开步骤详情' },
  { source: 'Close step details', target: '关闭步骤详情' },
  { source: 'Ready to proceed', target: '准备继续' },
  { source: 'Proceed', target: '继续', uiOnly: true, wholeWord: true },
  { source: 'Proceed anyway', target: '仍然继续' },
  { source: 'Cancel and go back', target: '取消并返回' },
  { source: 'Return', target: '返回', uiOnly: true, wholeWord: true },
  { source: 'Done!', target: '完成！' },
  { source: 'All set', target: '已就绪' },
  { source: 'Everything is up to date', target: '一切都是最新' },
  { source: 'No updates available', target: '暂无可用更新' },
  { source: 'Update now', target: '立即更新' },
  { source: 'Update later', target: '稍后更新' },
  { source: 'Checking for updates', target: '检查更新中' },
  { source: 'Update completed', target: '更新完成' },
  { source: 'Update cancelled', target: '更新已取消' },
  { source: 'Open update log', target: '打开更新日志' },
  { source: 'Release notes', target: '发行说明' },
  { source: 'What\'s new', target: '新功能' },
  { source: 'No release notes', target: '无发行说明' },
  { source: 'Thanks for using', target: '感谢使用' },
  { source: 'See you next time', target: '下次再见' },
  { source: 'Goodbye', target: '再见', uiOnly: true, wholeWord: true },
  { source: 'Bye', target: '再见', uiOnly: true, wholeWord: true },
]
